global:
  storageclass: longhorn
  image:
    registry: ''
    secretType: dockerconfigjson

cron:
  # Run hourly, 20 minutes after the top of the hour.
  schedule: '20 * * * *'

  image:
    name: ddns
    tag: 1.0.0
    pullSecrets: []

  env:
  - name: AWS_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: terraform
        key: AWS_ACCESS_KEY
  - name: AWS_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: terraform
        key: AWS_SECRET_KEY
  - name: AWS_REGION
    valueFrom:
      secretKeyRef:
        name: terraform
        key: AWS_REGION
  - name: CRONITOR_TELEMETRY_KEY
    valueFrom:
      secretKeyRef:
        name: cronitor
        key: CRONITOR_TELEMETRY_KEY
  - name: DEVELOPMENT_A_RECORD
    valueFrom:
      secretKeyRef:
        name: terraform
        key: DEVELOPMENT_A_RECORD

  resources:
    requests:
      memory: 1Gi
      cpu: 0.25
    limits:
      memory: 1Gi
      cpu: 0.25

  annotations: {}
  labels: {}

  securityContext:
    runAsUser: 1001
    fsGroup: ddns
    fsGroupChangePolicy: OnRootMismatch

volume:
  enabled: true
  size: 2Gi