_extends: .github-private

repository:
  name: ddns
  description: Dynamic DNS cronjob to update an A record in AWS with my residential IP
  homepage: https://github.com/premiscale/ddns
  topics: dns, aws, terraform, cron