fail_fast: true
repos:
  # Requires hadolint binary on local machine.
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint
        args:
          - --config
          - .hadolint.yaml
          - -t
          - error
          - ddns/Dockerfile

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=10000, --enforce-all]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        args:
          - -x

  - repo: https://github.com/bjd2385/dynamic-continuation-orb
    rev: v3.6.10
    hooks:
      - id: circleci-config-validate

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: helmlint

  - repo: https://github.com/premiscale/pre-commit-hooks
    rev: v0.0.9
    hooks:
    -   id: msg-issue-prefix

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.2
    hooks:
     - id: terraform_fmt
       args:
         - --args=-no-color
         - --args=-diff
         - --args=-write=false