version: 2.1

setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.7.1
  general: bjd2385/general@0.7.7
  slack: circleci/slack@4.12.5


workflows:
  ddns:
    jobs:
      - dynamic/continue:
          context: circleci

      - slack/on-hold:
          context: slack
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - request-approval:
          requires:
            - slack/on-hold
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/github-release:
          name: Create GitHub release from tag
          context: github
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/helm-release-nexus:
          name: helm build and push [helm/ddns] [tag]
          context: nexus
          path: helm/ddns
          requires:
            - request-approval
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/docker-nexus:
          name: docker [ddns] [tag]
          context: nexus
          image-name: ddns
          args: --build-arg TERRAFORM_VERSION=1.3.4
          commit-tag: false
          path: ddns/
          tag: $CIRCLE_TAG
          requires:
            - request-approval
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/helm-upgrade:
          name: helm upgrade install [helm/ddns] [tag]
          cluster: $CHELSEA_CLUSTER
          namespace: crons
          repo: $HELM_REPOSITORY_URL
          additional-values: |
            --set global.image.registry="$DOCKER_DOMAIN" --set cron.image.pullSecrets[0]=nexus-docker-registry
          requires:
            - helm build and push [helm/ddns] [tag]
            - docker [ddns] [tag]
          context:
            - kubeconfig
            - nexus
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/