version: 2.1


orbs:
  general: bjd2385/general@0.7.7


workflows:
  ddns:
    jobs:
      - general/docker-nexus:
          name: docker build and push [ddns/] [develop]
          context: nexus
          image-name: ddns
          args: --build-arg TERRAFORM_VERSION=1.3.4
          commit-tag: false
          path: ddns/
          tag: 0.0.<< pipeline.number >>
          nexus-domain: $DOCKER_DEVELOP_DOMAIN
          filters:
            branches:
              ignore:
                - master

      - general/docker-nexus:
          name: docker build and push [ddns/] [master]
          context: nexus
          image-name: ddns
          args: --build-arg TERRAFORM_VERSION=1.3.4
          commit-tag: false
          path: ddns/Dockerfile
          tag: 0.0.<< pipeline.number >>
          nexus-domain: $DOCKER_MASTER_DOMAIN
          filters:
            branches:
              only:
                - master