version: 2.1


orbs:
  general: bjd2385/general@0.7.2


workflows:
  helm-ddns:
    jobs:
      - general/helm-lint:
          name: helm lint [helm/ddns]
          chart-path: helm/ddns

      - general/helm-release-nexus:
          name: helm build and push [helm/ddns] [develop]
          context: nexus
          path: helm/ddns
          repo-name: premiscale
          repo: $HELM_DEVELOP_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          # image-tag: 0.0.<< pipeline.number >>
          # image-tag-path: .influxdb.image.tag
          requires:
            - helm lint [helm/ddns]
          filters:
            branches:
              ignore:
                - master

      - general/helm-release-nexus:
          name: helm build and push [helm/ddns] [master]
          context: nexus
          path: helm/ddns
          repo-name: premiscale
          repo: $HELM_MASTER_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          # image-tag: 0.0.<< pipeline.number >>
          # image-tag-path: .influxdb.image.tag
          requires:
            - helm lint [helm/ddns]
          filters:
            branches:
              only:
                - master