version: 2.1


orbs:
  general: bjd2385/general@0.7.7


workflows:
  helm-ddns:
    jobs:
      - general/helm-lint:
          name: helm lint [helm/ddns]
          chart-path: helm/ddns

      - general/docker-nexus:
          name: docker build and push [ddns/] [develop]
          context: nexus
          image-name: ddns
          args: --build-arg TERRAFORM_VERSION=1.3.4
          commit-tag: false
          path: ddns/
          tag: 0.0.<< pipeline.number >>
          nexus-domain: $DOCKER_DEVELOP_DOMAIN
          filters:
            branches:
              ignore:
                - master

      - general/docker-nexus:
          name: docker build and push [ddns/] [master]
          context: nexus
          image-name: ddns
          args: --build-arg TERRAFORM_VERSION=1.3.4
          commit-tag: false
          path: ddns/Dockerfile
          tag: 0.0.<< pipeline.number >>
          nexus-domain: $DOCKER_MASTER_DOMAIN
          filters:
            branches:
              only:
                - master

      - general/helm-release-nexus:
          name: helm build and push [helm/ddns] [develop]
          context: nexus
          path: helm/ddns
          repo: $HELM_DEVELOP_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          # image-tag: 0.0.<< pipeline.number >>
          # image-tag-path: .influxdb.image.tag
          requires:
            - helm lint [helm/ddns]
          filters:
            branches:
              ignore:
                - master

      - general/helm-release-nexus:
          name: helm build and push [helm/ddns] [master]
          context: nexus
          path: helm/ddns
          repo: $HELM_MASTER_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          # image-tag: 0.0.<< pipeline.number >>
          # image-tag-path: .influxdb.image.tag
          requires:
            - helm lint [helm/ddns]
          filters:
            branches:
              only:
                - master